import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { batchWrite } from "../dynamodb/batch-write";
import { extract } from "../tar/extract";

const client = new DynamoDBClient()

/**
 * Reads the data file (generated by get command) and inserts all
 * found data into the specified DynamoDB table
 *
 * @param tableName Name of the DynamoDB table to insert into
 * @param filePath File path to pull archived items from
 */
export const insertDynamoData = async(tableName: string, filePath: string) => {
    let totalCount = 0
    await extract(filePath, data => {
        const items = JSON.parse(data.toString('utf-8'))
        if (Array.isArray(items)) {
            totalCount += items.length
            return batchWrite(client, tableName, items)
        } else {
            // If the file was generated by the <get> command, shouldn't get here
            console.warn("Encountered entry with non-array data, skipping")
        }
    })
    console.log("# items:", totalCount);
}